### ISSUE TITLE
Check Styling Flake8

### ISSUE THREAD

**Issue by AndresPitta** [UBC-MDS/pysketball#42]
- [x] nba_stats

- [x] nba_ranking

- [x] nba_boxplot

- [x] nba_scraper

- [x] test_nba_stats

- [x] test_nba_ranking

- [x] test_nba_boxplot

- [x] test_nba_scraper

We still need to check style for new test!

**Comment by vanandsh** [comment]
All files in adherence with PEP8 styling - verified
